---
- name: Verificar runAsUser.type en SCC (PCI-DSS)
  hosts: localhost
  gather_facts: no
  
  tasks:
    - command: oc login -u admin -p OTQ3MzMx https://api.cluster-4sppc.dynamic.redhatworkshops.io:6443 --insecure-skip-tls-verify
    
    - name: Obtener todas las SCC
      kubernetes.core.k8s_info:
        api_version: security.openshift.io/v1
        kind: SecurityContextConstraints
      register: sccs

    - name: Listar SCC que NO cumplen con MustRunAsRange
      debug:
        msg: "{{ item.metadata.name }}"
      loop: "{{ sccs.resources }}"
      when: item.runAsUser.type | default('') != 'MustRunAsRange'
      register: salida

    - set_fact:
        scc: |
          {{ salida.results
          | selectattr('skipped', 'undefined')
          | map(attribute='item.metadata.name')
          | list }}

    - name: salida SCC
      debug: 
        msg: "{{ scc }}"

    - name: Obtener Pods del cluster
      k8s_info:
        api_version: v1
        kind: Pod
      register: pods

    - name: Filtrar Pods con SCC inválidos
      set_fact:
        pods_con_scc_invalido: >
          {{ pods.resources
          | selectattr('metadata.annotations."openshift.io/scc"','in', scc_list)
          | list }}
    
    - name: Mostrar Pods que utilizan SCC inválidos
      debug:
        msg: "{{ item.metadata.namespace }}/{{ item.metadata.name }} usa el SCC {{ item.metadata.annotations['openshift.io/scc'] }}"
      loop: "{{ pods_con_scc_invalido }}"
