---
- name: Verificar runAsUser.type en SCC (PCI-DSS)
  hosts: localhost
  gather_facts: no
  
  tasks:
    - command: oc login -u admin -p OTQ3MzMx https://api.cluster-4sppc.dynamic.redhatworkshops.io:6443 --insecure-skip-tls-verify
    
    - name: Obtener todas las SCC
      kubernetes.core.k8s_info:
        api_version: security.openshift.io/v1
        kind: SecurityContextConstraints
      register: sccs
    - debug:
        msg: "{{ sccs }}"
