---
- name: Revisión informativa de controles de seguridad OpenShift y generación de reporte
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    kubeadmin_secret: kubeadmin
    kube_system_ns: kube-system
    logging_ns: openshift-logging
    ingress_ns: openshift-ingress-operator

    report_dir: /tmp/ocp-reports
    report_name: "reporte-ocp-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "xukt zkki wrwx jiyp"
    smtp_host: smtp.gmail.com

    send_webhook: false
    webhook_url: https://webhook.empresa.cl/ocp/report

  tasks:

    # =========================================================
    # INICIALIZACIÓN
    # =========================================================

    - name: Inicializar variables
      set_fact:
        identity_providers: []
        kubeadmin_resultado: ""
        clf_items: []
        clf_exists: false
        clf_name: ""
        audit_configured: false
        node_count: 0
        clf_pod_count: 0
        clf_resultado: ""
        ingress_resultado: ""
        ldap_idps: []
        ldap_resultado: ""

    # =========================================================
    # KUBEADMIN / OAUTH
    # =========================================================

    - name: Verificar existencia del secreto kubeadmin
      command: oc get secret {{ kubeadmin_secret }} -n {{ kube_system_ns }}
      register: kubeadmin_cmd
      failed_when: false

    - name: Obtener OAuth
      command: oc get oauth cluster -o json
      register: oauth_cmd
      failed_when: false

    - name: Parsear OAuth
      set_fact:
        oauth_json: "{{ oauth_cmd.stdout | from_json }}"
      when: oauth_cmd.rc == 0 and oauth_cmd.stdout | length > 0

    - name: Extraer Identity Providers
      set_fact:
        identity_providers: "{{ oauth_json.spec.identityProviders | default([]) }}"
      when: oauth_cmd.rc == 0

    - name: Definir resultado kubeadmin
      set_fact:
        kubeadmin_resultado: >-
          {% if kubeadmin_cmd.rc != 0 %}
          KUBEADMIN NO EXISTE
          {% elif identity_providers | length == 0 %}
          KUBEADMIN EXISTE - IDP NO CONFIGURADO
          {% else %}
          KUBEADMIN EXISTE - IDP CONFIGURADO
          {% endif %}

    # =========================================================
    # CLUSTER LOG FORWARDER
    # =========================================================

    - name: Obtener CLF
      command: oc get clusterlogforwarder -n {{ logging_ns }} -o json
      register: clf_cmd
      failed_when: false

    - name: Parsear CLF
      set_fact:
        clf_json: "{{ clf_cmd.stdout | from_json }}"
      when: clf_cmd.rc == 0 and clf_cmd.stdout | length > 0

    - name: Definir CLF
      set_fact:
        clf_items: "{{ clf_json.items | default([]) }}"
        clf_exists: "{{ clf_json.items | default([]) | length > 0 }}"
      when: clf_cmd.rc == 0

    - name: Extraer nombre CLF
      set_fact:
        clf_name: "{{ clf_items[0].metadata.name }}"
      when: clf_exists

    - name: Validar AUDIT
      set_fact:
        audit_configured: >-
          {{
            clf_items[0].spec.inputs | default([])
            | selectattr('type', 'equalto', 'audit')
            | list | length > 0
          }}
      when: clf_exists

    - name: Definir resultado CLF
      set_fact:
        clf_resultado: >-
          {% if not clf_exists %}
          CLF NO EXISTE
          {% elif not audit_configured %}
          CLF {{ clf_name }} SIN AUDIT
          {% else %}
          CLF {{ clf_name }} CON AUDIT
          {% endif %}

    # =========================================================
    # INGRESS TLS
    # =========================================================

    - name: Obtener TLS Ingress
      command: oc get ingresscontrollers/default -n {{ ingress_ns }} -o jsonpath='{.status.tlsProfile.ciphers}'
      register: ingress_tls_cmd
      failed_when: false

    - name: Definir resultado Ingress
      set_fact:
        ingress_resultado: >-
          TLS CIPHERS:
          {{ ingress_tls_cmd.stdout if ingress_tls_cmd.stdout | length > 0 else "NO DEFINIDOS" }}

    # =========================================================
    # LDAP TLS
    # =========================================================

    - name: Filtrar LDAP
      set_fact:
        ldap_idps: "{{ identity_providers | selectattr('type', 'equalto', 'LDAP') | list }}"

    - name: Definir resultado LDAP
      set_fact:
        ldap_resultado: >-
          {% if ldap_idps | length == 0 %}
          NO EXISTEN LDAP
          {% else %}
          {% for idp in ldap_idps %}
          LDAP {{ idp.name }} - insecure={{ idp.ldap.insecure | default(false) }}
          {% endfor %}
          {% endif %}

    # =========================================================
    # REPORTE
    # =========================================================

    - name: Construir reporte texto
      set_fact:
        report_text: |
          REPORTE DE SEGURIDAD OPENSHIFT
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}

          KUBEADMIN
          {{ kubeadmin_resultado }}

          CLUSTER LOG FORWARDER
          {{ clf_resultado }}

          INGRESS TLS
          {{ ingress_resultado }}

          LDAP TLS
          {{ ldap_resultado }}

    - name: Crear directorio
      file:
        path: "{{ report_dir }}"
        state: directory

    - name: Guardar reporte TXT
      copy:
        dest: "{{ report_dir }}/{{ report_name }}.txt"
        content: "{{ report_text }}"

    # =========================================================
    # ENVÍO
    # =========================================================

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        port: 587
        to: "{{ mail_to }}"
        subject: "Reporte Seguridad OpenShift"
        body: "{{ report_text }}"
      when: send_mail

    - name: Enviar reporte por webhook
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body:
          report: "{{ report_text }}"
        body_format: json
      when: send_webhook
