---
- name: Revisión informativa de controles de seguridad OpenShift y generación de reporte
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    ingress_ns: openshift-ingress-operator
    report_dir: /tmp/ocp-reports
    report_name: "reporte-ocp-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

    send_webhook: false
    webhook_url: https://webhook.empresa.cl/ocp/report

    system_ns_regex: "^(openshift.*|kube.*|default|stackrox)$"

  tasks:
    # =========================================================
    # RECOLECCIÓN DE DATOS
    # =========================================================
    - name: "Obtener infraestructura del cluster"
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: "Obtener configuración OAuth"
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: OAuth
        name: cluster
      register: oauth_info

    - name: "Obtener todos los OAuthClients"
      kubernetes.core.k8s_info:
        api_version: oauth.openshift.io/v1
        kind: OAuthClient
      register: oauth_clients

    - name: "Obtener recursos de Red"
      kubernetes.core.k8s_info:
        api_version: "{{ item.api }}"
        kind: "{{ item.kind }}"
      loop:
        - { api: "v1", kind: "Namespace" }
        - { api: "networking.k8s.io/v1", kind: "NetworkPolicy" }
      register: net_resources

    - name: "Obtener otros recursos de seguridad"
      kubernetes.core.k8s_info:
        api_version: "{{ item.api }}"
        kind: "{{ item.kind }}"
        name: "{{ item.name | default(omit) }}"
        namespace: "{{ item.ns | default(omit) }}"
      loop:
        - { api: "v1", kind: "Secret", name: "kubeadmin", ns: "kube-system" }
        - { api: "logging.openshift.io/v1", kind: "ClusterLogForwarder", ns: "openshift-logging" }
        - { api: "apps/v1", kind: "Deployment", name: "sensor", ns: "stackrox" }
        - { api: "operators.coreos.com/v1alpha1", kind: "Subscription", name: "container-security-operator", ns: "openshift-operators" }
        - { api: "operator.openshift.io/v1", kind: "IngressController", name: "default", ns: "openshift-ingress-operator" }
      register: sec_resources

    # =========================================================
    # LÓGICA DE PROCESAMIENTO (FACTS)
    # =========================================================
    - name: "Procesar variables para el reporte"
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('DESCONOCIDO') }}"
        ns_list: "{{ net_resources.results[0].resources }}"
        netpol_list: "{{ net_resources.results[1].resources }}"
        kubeadmin_info: "{{ sec_resources.results[0].resources }}"
        clf_info: "{{ sec_resources.results[1].resources }}"
        acs_info: "{{ sec_resources.results[2].resources }}"
        cso_info: "{{ sec_resources.results[3].resources }}"
        ingress_info: "{{ sec_resources.results[4].resources }}"
        identity_providers: "{{ oauth_info.resources[0].spec.identityProviders | default([]) }}"
        global_timeout: "{{ oauth_info.resources[0].spec.tokenConfig.accessTokenInactivityTimeout | default('NO CONFIGURADO') }}"

    - name: "Generar Listados de Red y OAuth"
      set_fact:
        netpol_protegidos: |-
          {% set lines = [] %}
          {% set target_ns = ns_list | map(attribute='metadata.name') | reject('match', system_ns_regex) | list %}
          {% for ns in target_ns | sort %}
            {% set ns_pols = netpol_list | selectattr('metadata.namespace', 'equalto', ns) | map(attribute='metadata.name') | list %}
            {% if ns_pols | length > 0 %}{% set _ = lines.append('Namespace: ' + ns + ' (Políticas: ' + ns_pols | join(', ') + ')') %}{% endif %}
          {% endfor %}
          {{ lines | join('\n') if lines | length > 0 else 'No se encontraron namespaces protegidos.' }}
        netpol_expuestos: |-
          {% set lines = [] %}
          {% set target_ns = ns_list | map(attribute='metadata.name') | reject('match', system_ns_regex) | list %}
          {% for ns in target_ns | sort %}
            {% set ns_pols = netpol_list | selectattr('metadata.namespace', 'equalto', ns) | list %}
            {% if ns_pols | length == 0 %}{% set _ = lines.append('Namespace: ' + ns) %}{% endif %}
          {% endfor %}
          {{ lines | join('\n') if lines | length > 0 else 'Todos los namespaces están protegidos.' }}
        oauth_clients_list: |-
          {% set lines = [] %}
          {% for client in oauth_clients.resources | sort(attribute='metadata.name') %}
            {% set c_tout = client.accessTokenInactivityTimeoutSeconds | default('N/A') %}
            {% set _ = lines.append('Cliente: ' + client.metadata.name + '\nTimeout: ' + c_tout | string + ' s\n---------------------------------------------') %}
          {% endfor %}
          {{ lines | join('\n') }}

    # =========================================================
    # CONSTRUCCIÓN DEL REPORTE (Ajuste de indentación)
    # =========================================================
    - name: "Construir contenido del reporte"
      set_fact:
        report_text: |
          REPORTE DE SEGURIDAD OPENSHIFT
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}

          ---------------------------------
          KUBEADMIN
          Ensure that the kubeadmin secret has been removed - ocp4-pci-dss-4-0-kubeadmin-removed
          {% if kubeadmin_info | length == 0 %}
          El secreto kubeadmin NO EXISTE
          {% else %}
          El secreto kubeadmin EXISTE (IdentityProviders: {{ identity_providers | length }})
          {% endif %}

          ---------------------------------
          CLUSTER LOG FORWARDER
          Ensure that Audit Log Forwarding Is Enabled - ocp4-pci-dss-4-0-audit-log-forwarding-enabled
          {% if clf_info | length == 0 %}
          La instancia ClusterLogForwarder (CLF) NO EXISTE
          {% else %}
          {% set audit_on = clf_info[0].spec.inputs | default([]) | selectattr('type', 'equalto', 'audit') | list | length > 0 %}
          Instancia: {{ clf_info[0].metadata.name }} - {{ 'CON AUDIT LOGS' if audit_on else 'SIN AUDIT LOGS' }}
          {% endif %}

          ---------------------------------
          INGRESS CONTROLLER TLS
          Ensure that the Ingress Controller only makes use of Strong - ocp4-pci-dss-4-0-ingress-controller-tls-cipher-suites
          {% if ingress_info | length > 0 %}
          Listado de TLS configurados en ingresscontrollers/default:
          {% for cipher in ingress_info[0].status.tlsProfile.ciphers | default([]) %}
          - {{ cipher }}
          {% endfor %}
          {% else %}
          No se encontró ingresscontrollers/default
          {% endif %}

          ---------------------------------
          LDAP IDENTITY PROVIDERS TLS
          Only Use LDAP-based IdPs with TLS - ocp4-pci-dss-4-0-ocp-no-ldap-insecure
          {% set ldaps = identity_providers | selectattr('type', 'equalto', 'LDAP') | list %}
          {% if ldaps | length == 0 %}
          Protocolo LDAP NO configurado.
          {% else %}
          {% for idp in ldaps %}
          LDAP: {{ idp.name }} - insecure: {{ idp.ldap.insecure | default(false) }}
          {% endfor %}
          {% endif %}

          ---------------------------------
          ACS SENSOR
          Ensure that Advanced Cluster Security (ACS) Sensor is deployed - ocp4-pci-dss-4-0-acs-sensor-exists
          {{ 'ACS Sensor detectado y operativo en namespace stackrox.' if acs_info | length > 0 else 'ACS Sensor no detectado.' }}

          ---------------------------------
          NETWORK POLICIES
          Ensure that application Namespaces have Network Policies defined - ocp4-pci-dss-4-0-configure-network-policies-namespaces

          1. NAMESPACES CON NETWORK POLICIES DEFINIDAS
          ---------------------------------------------
          {{ netpol_protegidos | indent(width=0) }}

          2. NAMESPACES SIN NETWORK POLICIES (EXPUESTOS)
          ---------------------------------------------
          {{ netpol_expuestos | indent(width=0) }}

          ---------------------------------
          CONTAINER SECURITY OPERATOR
          Make sure the Container Security Operator is installed - ocp4-pci-dss-4-0-container-security-operator-exists
          {{ 'Instalado: ' + cso_info[0].status.installedCSV if cso_info | length > 0 else 'CSO Operator NO instalado.' }}

          ---------------------------------
          OAUTH INACTIVITY TIMEOUT
          Configure OAuth tokens to expire after a set period of inactivity - ocp4-pci-dss-4-0-oauth-or-oauthclient-inactivity-timeout

          1. CONFIGURACIÓN GLOBAL (OAuth Server)
          ---------------------------------------------
          Timeout Actual: {{ global_timeout }}

          2. DETALLE DE CLIENTES (OAuthClients)
          ---------------------------------------------
          {{ oauth_clients_list | indent(width=0) }}

    - name: "Guardar y Enviar Reporte"
      block:
        - file: { path: "{{ report_dir }}", state: directory }
        - copy: { dest: "{{ report_dir }}/{{ report_name }}.txt", content: "{{ report_text }}" }
        - community.general.mail:
            host: "{{ smtp_host }}"
            username: "{{ mail_from }}"
            password: "{{ mail_password }}"
            port: 587
            to: "{{ mail_to }}"
            subject: "Seguridad OpenShift Consolidado - {{ cluster_name }}"
            body: "{{ report_text }}"
            secure: starttls
          when: send_mail | bool
