#############################
# FUNCIONAL / CONSOLIDADO / CORREGIDO
#############################
---
- name: Revisión informativa de controles de seguridad OpenShift y generación de reporte
  hosts: localhost
  gather_facts: no
  connection: local

  vars:

    report_dir: /tmp/ocp-reports
    report_name: "reporte-ocp-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "xukt zkki wrwx jiyp"
    smtp_host: smtp.gmail.com

    send_webhook: false
    webhook_url: https://webhook.empresa.cl/ocp/report

  tasks:

    # =========================================================
    # INICIALIZACIÓN
    # =========================================================

    - name: Inicializar variables
      set_fact:
        cluster_name: DESCONOCIDO
        identity_providers: []
        kubeadmin_resultado: ""
        clf_items: []
        clf_exists: false
        clf_name: ""
        audit_configured: false
        clf_resultado: ""
        tls_ciphers: []
        ingress_tls_resultado: ""
        ldap_idps: []
        ldap_resultado: ""

    # =========================================================
    # NOMBRE DEL CLUSTER
    # =========================================================

    - name: Obtener infraestructura del cluster
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: >-
          {{
            infra_info.resources[0].status.infrastructureName
            | default('DESCONOCIDO')
          }}

    # =========================================================
    # KUBEADMIN / OAUTH
    # =========================================================

    - name: Obtener secreto kubeadmin
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: kubeadmin
        namespace: kube-system
      register: kubeadmin_info
      failed_when: false

    - name: Definir existencia de kubeadmin
      set_fact:
        kubeadmin_exists: "{{ kubeadmin_info.resources | default([]) | length > 0 }}"

    - name: Obtener configuración OAuth
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: OAuth
        name: cluster
      register: oauth_info
      failed_when: false

    - name: Extraer Identity Providers
      set_fact:
        identity_providers: "{{ oauth_info.resources[0].spec.identityProviders | default([]) }}"
      when:
        - oauth_info.resources is defined
        - oauth_info.resources | length > 0

    - name: Definir resultado kubeadmin
      set_fact:
        kubeadmin_resultado: >-
          {% if not kubeadmin_exists %}
          El secreto kubeadmin NO EXISTE
          {% elif identity_providers | length == 0 %}
          El secreto kubeadmin EXISTE - IdentityProvider NO CONFIGURADO
          {% else %}
          El secreto kubeadmin EXISTE - IdentityProvider CONFIGURADO
          {% endif %}

    # =========================================================
    # CLUSTER LOG FORWARDER
    # =========================================================

    - name: Obtener ClusterLogForwarder
      kubernetes.core.k8s_info:
        api_version: logging.openshift.io/v1
        kind: ClusterLogForwarder
        namespace: openshift-logging
      register: clf_info
      failed_when: false

    - name: Definir CLF existente
      set_fact:
        clf_items: "{{ clf_info.resources | default([]) }}"
        clf_exists: "{{ clf_info.resources | default([]) | length > 0 }}"

    - name: Extraer nombre CLF
      set_fact:
        clf_name: "{{ clf_items[0].metadata.name }}"
      when: clf_exists

    - name: Validar configuración AUDIT
      set_fact:
        audit_configured: >-
          {{
            clf_items[0].spec.inputs | default([])
            | selectattr('type', 'equalto', 'audit')
            | list | length > 0
          }}
      when: clf_exists

    - name: Definir resultado CLF
      set_fact:
        clf_resultado: >-
          {% if not clf_exists %}
          La instancia ClusterLogForwarder (CLF) del Operador ClusterLogging NO EXISTE
          {% elif not audit_configured %}
          La instancia ClusterLogForwarder existe - Nombre: {{ clf_name }} - SIN AUDIT LOGS
          {% else %}
          La instancia ClusterLogForwarder existe - Nombre: {{ clf_name }} - CON AUDIT LOGS
          {% endif %}

    # =========================================================
    # INGRESS CONTROLLER TLS
    # =========================================================

    - name: Obtener IngressController default
      kubernetes.core.k8s_info:
        api_version: operator.openshift.io/v1
        kind: IngressController
        name: default
        namespace: openshift-ingress-operator
      register: ingress_info
      failed_when: false

    - name: Extraer TLS ciphers efectivos
      set_fact:
        tls_ciphers: "{{ ingress_info.resources[0].status.tlsProfile.ciphers | default([]) }}"
      when:
        - ingress_info.resources is defined
        - ingress_info.resources | length > 0

    - name: Definir resultado Ingress TLS
      set_fact:
        ingress_tls_resultado: >-
          {% if tls_ciphers | length == 0 %}
          NO SE ENCUENTRAN CIPHERS TLS CONFIGURADOS EN ingresscontrollers/default
          {% else %}
          CIPHERS TLS CONFIGURADOS EN ingresscontrollers/default:
          {% for cipher in tls_ciphers %}
          - {{ cipher }}
          {% endfor %}
          {% endif %}

    # =========================================================
    # LDAP IDENTITY PROVIDERS TLS
    # =========================================================

    - name: Filtrar Identity Providers LDAP
      set_fact:
        ldap_idps: "{{ identity_providers | selectattr('type', 'equalto', 'LDAP') | list }}"

    - name: Definir resultado LDAP
      set_fact:
        ldap_resultado: >-
          {% if ldap_idps | length == 0 %}
          LDAPS NO configurados como IdentityProviders en oauth/cluster
          {% else %}
          {% for idp in ldap_idps %}
          LDAP Configurado - Nombre: {{ idp.name }} - insecure: {{ idp.ldap.insecure | default(false) }}
          {% endfor %}
          {% endif %}

    # =========================================================
    # REPORTE
    # =========================================================

    - name: Construir reporte en texto
      set_fact:
        report_text: |
          REPORTE DE SEGURIDAD OPENSHIFT
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}

          ---------------------------------
          KUBEADMIN
          Ensure that the kubeadmin secret has been removed -	ocp4-pci-dss-4-0-kubeadmin-removed
          {{ kubeadmin_resultado }}

          ---------------------------------
          CLUSTER LOG FORWARDER
          Ensure that Audit Log Forwarding Is Enabled	- ocp4-pci-dss-4-0-audit-log-forwarding-enabled
          {{ clf_resultado }}

          ---------------------------------
          INGRESS CONTROLLER TLS
          Ensure that the Ingress Controller only makes use of Strong -	ocp4-pci-dss-4-0-ingress-controller-tls-cipher-suites
          Listado de TLS configruados en ingresscontrollers/default
          {{ ingress_tls_resultado }}

          ---------------------------------
          LDAP IDENTITY PROVIDERS TLS
          Only Use LDAP-based IdPs with TLS	- ocp4-pci-dss-4-0-ocp-no-ldap-insecure
          {{ ldap_resultado }}

    - name: Crear directorio de reportes
      file:
        path: "{{ report_dir }}"
        state: directory

    - name: Guardar reporte TXT
      copy:
        dest: "{{ report_dir }}/{{ report_name }}.txt"
        content: "{{ report_text }}"

    # =========================================================
    # ENVÍO
    # =========================================================

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        port: 587
        to: "{{ mail_to }}"
        subject: "Reporte Seguridad OpenShift - {{ cluster_name }}"
        body: "{{ report_text }}"
      when: send_mail

    - name: Enviar reporte por webhook
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body:
          cluster: "{{ cluster_name }}"
          report: "{{ report_text }}"
        body_format: json
      when: send_webhook
