#############################  FUNCIONAL / PROBADO EN LABORATORIO
---
- name: Revisión informativa de controles de seguridad OpenShift y generación de reporte
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    kubeadmin_secret: kubeadmin
    kube_system_ns: kube-system
    logging_ns: openshift-logging
    ingress_ns: openshift-ingress-operator

    report_dir: /tmp/ocp-reports
    report_name: "reporte-ocp-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "xukt zkki wrwx jiyp"
    smtp_host: smtp.gmail.com

    send_webhook: false
    webhook_url: https://webhook.empresa.cl/ocp/report

  tasks:

    # =========================================================
    # INICIALIZACIÓN
    # =========================================================

    - name: Inicializar variables
      set_fact:
        cluster_name: DESCONOCIDO
        identity_providers: []
        kubeadmin_resultado: ""
        clf_items: []
        clf_exists: false
        clf_name: ""
        audit_configured: false
        clf_resultado: ""
        tls_ciphers: ""
        ldap_idps: []
        ldap_resultado: ""

    # =========================================================
    # NOMBRE DEL CLUSTER
    # =========================================================

    - name: Obtener información de infraestructura del cluster
      command: oc get infrastructure cluster -o json
      register: infra_cmd
      failed_when: false

    - name: Parsear infraestructura
      set_fact:
        infra_json: "{{ infra_cmd.stdout | from_json }}"
      when: infra_cmd.rc == 0 and infra_cmd.stdout | length > 0

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: "{{ infra_json.status.infrastructureName | default('DESCONOCIDO') }}"
      when: infra_cmd.rc == 0

    # =========================================================
    # KUBEADMIN / OAUTH
    # =========================================================

    - name: Verificar existencia del secreto kubeadmin
      command: oc get secret {{ kubeadmin_secret }} -n {{ kube_system_ns }}
      register: kubeadmin_cmd
      failed_when: false

    - name: Obtener OAuth
      command: oc get oauth cluster -o json
      register: oauth_cmd
      failed_when: false

    - name: Parsear OAuth
      set_fact:
        oauth_json: "{{ oauth_cmd.stdout | from_json }}"
      when: oauth_cmd.rc == 0 and oauth_cmd.stdout | length > 0

    - name: Extraer Identity Providers
      set_fact:
        identity_providers: "{{ oauth_json.spec.identityProviders | default([]) }}"
      when: oauth_cmd.rc == 0

    - name: Definir resultado kubeadmin
      set_fact:
        kubeadmin_resultado: >-
          {% if kubeadmin_cmd.rc != 0 %}
          El secreto kubeadmin NO EXISTE
          {% elif identity_providers | length == 0 %}
          El secreto kubeadmin EXISTE - IdentityProvider se encuentra NO CONFIGURADO
          {% else %}
          El secreto kubeadmin EXISTE - IdentityProvider se encuentra CONFIGURADO
          {% endif %}

    # =========================================================
    # CLUSTER LOG FORWARDER
    # =========================================================

    - name: Obtener ClusterLogForwarder
      command: oc get clusterlogforwarder -n {{ logging_ns }} -o json
      register: clf_cmd
      failed_when: false

    - name: Parsear CLF
      set_fact:
        clf_json: "{{ clf_cmd.stdout | from_json }}"
      when: clf_cmd.rc == 0 and clf_cmd.stdout | length > 0

    - name: Definir CLF existente
      set_fact:
        clf_items: "{{ clf_json.items | default([]) }}"
        clf_exists: "{{ clf_json.items | default([]) | length > 0 }}"
      when: clf_cmd.rc == 0

    - name: Extraer nombre CLF
      set_fact:
        clf_name: "{{ clf_items[0].metadata.name }}"
      when: clf_exists

    - name: Validar configuración AUDIT
      set_fact:
        audit_configured: >-
          {{
            clf_items[0].spec.inputs | default([])
            | selectattr('type', 'equalto', 'audit')
            | list | length > 0
          }}
      when: clf_exists

    - name: Definir resultado CLF
      set_fact:
        clf_resultado: >-
          {% if not clf_exists %}
          La instancia ClusterLogForwarder (CLF) del Operador ClusterLogging NO EXISTE
          {% elif not audit_configured %}
          La instancia ClusterLogForwarder existe - Nombre: {{ clf_name }} - CLF configurado SIN AUDIT LOGS
          {% else %}
          La instancia ClusterLogForwarder existe - Nombre: {{ clf_name }} - CLF configurado CON AUDIT LOGS
          {% endif %}

    # =========================================================
    # INGRESS CONTROLLER TLS
    # =========================================================

    - name: Obtener Ingress Controller
      command: >
        oc get ingresscontroller {{ ingress_name }}
        -n {{ ingress_ns }}
        -o json
      register: ingress_result
      failed_when: false

    - name: Extraer ciphers configurados
      set_fact:
        tls_ciphers: >-
          {{
            (ingress_result.stdout | from_json)['status']['tlsProfile']['ciphers']
            | default([])
          }}

    - name: Mostrar TLS configurados del cluster
      debug:
        msg: |
          CLUSTER: {{ inventory_hostname }}
          TLS CIPHERS CONFIGURADOS:
          {{ tls_ciphers }}

    # =========================================================
    # LDAP IDENTITY PROVIDERS TLS
    # =========================================================

    - name: Filtrar Identity Providers LDAP
      set_fact:
        ldap_idps: "{{ identity_providers | selectattr('type', 'equalto', 'LDAP') | list }}"

    - name: Definir resultado LDAP
      set_fact:
        ldap_resultado: >-
          {% if ldap_idps | length == 0 %}
          LDAPS NO configurados como IdentityProviders en oauth/cluster
          {% else %}
          {% for idp in ldap_idps %}
          LDAP Configurado - Nombre: {{ idp.name }} - Configuración insecure = {{ idp.ldap.insecure | default(false) }}
          {% endfor %}
          {% endif %}

    # =========================================================
    # REPORTE
    # =========================================================

    - name: Construir reporte en texto
      set_fact:
        report_text: |
          REPORTE DE SEGURIDAD OPENSHIFT
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}

          ---------------------------------
          KUBEADMIN
          Ensure that the kubeadmin secret has been removed -	ocp4-pci-dss-4-0-kubeadmin-removed
          {{ kubeadmin_resultado }}

          ---------------------------------
          CLUSTER LOG FORWARDER
          Ensure that Audit Log Forwarding Is Enabled	- ocp4-pci-dss-4-0-audit-log-forwarding-enabled
          {{ clf_resultado }}

          ---------------------------------
          INGRESS CONTROLLER TLS
          Ensure that the Ingress Controller only makes use of Strong -	ocp4-pci-dss-4-0-ingress-controller-tls-cipher-suites
          Listado de TLS configruados en ingresscontrollers/default
          {{ tls_ciphers }}

          ---------------------------------
          LDAP IDENTITY PROVIDERS TLS
          Only Use LDAP-based IdPs with TLS	- ocp4-pci-dss-4-0-ocp-no-ldap-insecure
          {{ ldap_resultado }}

    - name: Crear directorio de reportes
      file:
        path: "{{ report_dir }}"
        state: directory

    - name: Guardar reporte TXT
      copy:
        dest: "{{ report_dir }}/{{ report_name }}.txt"
        content: "{{ report_text }}"

    # =========================================================
    # ENVÍO
    # =========================================================

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        port: 587
        to: "{{ mail_to }}"
        subject: "Reporte Seguridad OpenShift - {{ cluster_name }}"
        body: "{{ report_text }}"
      when: send_mail

    - name: Enviar reporte por webhook
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body:
          cluster: "{{ cluster_name }}"
          report: "{{ report_text }}"
        body_format: json
      when: send_webhook
