---
- name: Revisión informativa de controles de seguridad OpenShift y generación de reporte
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    ingress_ns: openshift-ingress-operator
    report_dir: /tmp/ocp-reports
    report_name: "reporte-ocp-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    # CONFIGURACIÓN NOTIFICACIÓN
    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

    send_webhook: false
    webhook_url: https://webhook.empresa.cl/ocp/report

    # REGEX PARA NETWORK POLICIES (Omitir sistema y operadores core)
    system_ns_regex: "^(openshift.*|kube.*|default|stackrox)$"

  tasks:
    # =========================================================
    # INICIALIZACIÓN Y RECOLECCIÓN
    # =========================================================
    - name: Obtener infraestructura del cluster
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Obtener datos OAuth
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: OAuth
        name: cluster
      register: oauth_info

    - name: Obtener OAuthClients
      kubernetes.core.k8s_info:
        api_version: oauth.openshift.io/v1
        kind: OAuthClient
      register: oauth_clients

    - name: Obtener Namespaces y NetworkPolicies
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
      register: ns_list

    - name: Obtener NetPols
      kubernetes.core.k8s_info:
        api_version: networking.k8s.io/v1
        kind: NetworkPolicy
      register: netpol_list

    - name: Obtener secreto kubeadmin
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: kubeadmin
        namespace: kube-system
      register: kubeadmin_info

    - name: Obtener ClusterLogForwarder
      kubernetes.core.k8s_info:
        api_version: logging.openshift.io/v1
        kind: ClusterLogForwarder
        namespace: openshift-logging
      register: clf_info

    - name: Verificar ACS Sensor
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: sensor
        namespace: stackrox
      register: acs_sensor_check

    - name: Verificar CSO Operator
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: container-security-operator
        namespace: openshift-operators
      register: cso_sub

    - name: Obtener IngressController default
      kubernetes.core.k8s_info:
        api_version: operator.openshift.io/v1
        kind: IngressController
        name: default
        namespace: openshift-ingress-operator
      register: ingress_info

    # =========================================================
    # LÓGICA DE PROCESAMIENTO
    # =========================================================
    - name: Definir resultados base
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('DESCONOCIDO') }}"
        identity_providers: "{{ oauth_info.resources[0].spec.identityProviders | default([]) }}"
        global_timeout: "{{ oauth_info.resources[0].spec.tokenConfig.accessTokenInactivityTimeout | default('NO CONFIGURADO') }}"

    - name: Procesar Network Policies Detallado
      set_fact:
        netpol_protegidos: >-
          {% set target_ns = ns_list.resources | map(attribute='metadata.name') | reject('match', system_ns_regex) | list %}
          {% set lines = [] %}
          {% for ns in target_ns | sort %}
            {% set ns_pols = netpol_list.resources | selectattr('metadata.namespace', 'equalto', ns) | map(attribute='metadata.name') | list %}
            {% if ns_pols | length > 0 %}
              {% set _ = lines.append('   Namespace: ' + ns + ' (Políticas: ' + ns_pols | join(', ') + ')') %}
            {% endif %}
          {% endfor %}
          {{ lines | join('\n') if lines | length > 0 else '   No se encontraron namespaces protegidos.' }}
        netpol_expuestos: >-
          {% set target_ns = ns_list.resources | map(attribute='metadata.name') | reject('match', system_ns_regex) | list %}
          {% set lines = [] %}
          {% for ns in target_ns | sort %}
            {% set ns_pols = netpol_list.resources | selectattr('metadata.namespace', 'equalto', ns) | list %}
            {% if ns_pols | length == 0 %}
              {% set _ = lines.append('   Namespace: ' + ns) %}
            {% endif %}
          {% endfor %}
          {{ lines | join('\n') if lines | length > 0 else '   Todos los namespaces de aplicación están protegidos.' }}

    - name: Procesar Detalle OAuth Clients
      set_fact:
        oauth_clients_detail: >-
          {% set lines = [] %}
          {% for client in oauth_clients.resources | sort(attribute='metadata.name') %}
            {% set c_name = client.metadata.name %}
            {% set c_tout = client.accessTokenInactivityTimeoutSeconds | default('N/A') %}
            {% set _ = lines.append('Cliente: ' + c_name + '\nTimeout: ' + c_tout | string + ' s\n---------------------------------------------') %}
          {% endfor %}
          {{ lines | join('\n') }}

    # =========================================================
    # CONSTRUCCIÓN DEL REPORTE FINAL
    # =========================================================
    - name: Construir reporte final
      set_fact:
        report_text: |
          REPORTE DE SEGURIDAD OPENSHIFT
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}

          ---------------------------------
          KUBEADMIN
          Ensure that the kubeadmin secret has been removed - ocp4-pci-dss-4-0-kubeadmin-removed
          {% if kubeadmin_info.resources | length == 0 %}
          El secreto kubeadmin NO EXISTE
          {% elif identity_providers | length == 0 %}
          El secreto kubeadmin EXISTE - IdentityProvider NO CONFIGURADO
          {% else %}
          El secreto kubeadmin EXISTE - IdentityProvider CONFIGURADO
          {% endif %}

          ---------------------------------
          CLUSTER LOG FORWARDER
          Ensure that Audit Log Forwarding Is Enabled - ocp4-pci-dss-4-0-audit-log-forwarding-enabled
          {% if clf_info.resources | length == 0 %}
          La instancia ClusterLogForwarder (CLF) NO EXISTE
          {% else %}
          {% set audit_on = clf_info.resources[0].spec.inputs | default([]) | selectattr('type', 'equalto', 'audit') | list | length > 0 %}
          Instancia: {{ clf_info.resources[0].metadata.name }} - {{ 'CON AUDIT LOGS' if audit_on else 'SIN AUDIT LOGS' }}
          {% endif %}

          ---------------------------------
          INGRESS CONTROLLER TLS
          Ensure that the Ingress Controller only makes use of Strong - ocp4-pci-dss-4-0-ingress-controller-tls-cipher-suites
          {% if ingress_info.resources | length > 0 %}
          Ciphers en ingresscontrollers/default:
          {{ ingress_info.resources[0].status.tlsProfile.ciphers | default(['NO CONFIGURADO']) | join('\n- ') }}
          {% else %}
          Ingress Controller default no encontrado.
          {% endif %}

          ---------------------------------
          LDAP IDENTITY PROVIDERS TLS
          Only Use LDAP-based IdPs with TLS - ocp4-pci-dss-4-0-ocp-no-ldap-insecure
          {% set ldaps = identity_providers | selectattr('type', 'equalto', 'LDAP') | list %}
          {% if ldaps | length == 0 %}
          Protocolo LDAP NO configurado.
          {% else %}
          {% for idp in ldaps %}
          LDAP: {{ idp.name }} - insecure: {{ idp.ldap.insecure | default(false) }}
          {% endfor %}
          {% endif %}

          ---------------------------------
          ACS SENSOR
          Ensure that Advanced Cluster Security (ACS) Sensor is deployed - ocp4-pci-dss-4-0-acs-sensor-exists
          {{ 'ACS Sensor detectado y operativo en namespace stackrox.' if acs_sensor_check.resources | length > 0 else 'ACS Sensor no detectado.' }}

          ---------------------------------
          NETWORK POLICIES
          Ensure that application Namespaces have Network Policies defined - ocp4-pci-dss-4-0-configure-network-policies-namespaces

          1. NAMESPACES CON NETWORK POLICIES DEFINIDAS
          ---------------------------------------------
          {{ netpol_protegidos }}

          2. NAMESPACES SIN NETWORK POLICIES (EXPUESTOS)
          ---------------------------------------------
          {{ netpol_expuestos }}

          ---------------------------------
          CONTAINER SECURITY OPERATOR
          Make sure the Container Security Operator is installed - ocp4-pci-dss-4-0-container-security-operator-exists
          {{ 'Instalado: ' + cso_sub.resources[0].status.installedCSV if cso_sub.resources | length > 0 else 'CSO Operator NO instalado.' }}

          ---------------------------------
          OAUTH INACTIVITY TIMEOUT
          Configure OAuth tokens to expire after a set period of inactivity - ocp4-pci-dss-4-0-oauth-or-oauthclient-inactivity-timeout

          1. CONFIGURACIÓN GLOBAL (OAuth Server)
          ---------------------------------------------
          Timeout Actual: {{ global_timeout }}

          2. DETALLE DE CLIENTES (OAuthClients)
          ---------------------------------------------
          {{ oauth_clients_detail }}

    - name: Guardar y Enviar
      block:
        - file: { path: "{{ report_dir }}", state: directory }
        - copy: { dest: "{{ report_dir }}/{{ report_name }}.txt", content: "{{ report_text }}" }
        - community.general.mail:
            host: "{{ smtp_host }}"
            username: "{{ mail_from }}"
            password: "{{ mail_password }}"
            port: 587
