---
- name: Revisión avanzada de ClusterLogForwarder
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    logging_ns: "openshift-logging"

  tasks:

    - command: oc login --token=sha256~a7NNKc8Nu_eEFexkQ0TMZRsg2k7wCgs8f6LRbS4l4s0 --server=https://api.cluster-g9bkz.g9bkz.sandbox3232.opentlc.com:6443 --insecure-skip-tls-verify

    - name: Inicializar variables
      set_fact:
        clf_exists: false
        audit_configured: false
        pods_ok: false
        clf_name: ""
        node_count: 0
        clf_pod_count: 0

    # TASKS SEGURAS – detección del CLF
    - name: Obtener nombre del ClusterLogForwarder
      command: oc get clusterlogforwarder -n {{ logging_ns }} -o name
      register: clf_name_result
      failed_when: false

    - name: Definir existencia y nombre del CLF
      set_fact:
        clf_exists: "{{ clf_name_result.stdout | trim | length > 0 }}"
        clf_name: "{{ clf_name_result.stdout.split('/')[-1] }}"
      when: clf_name_result.stdout | trim | length > 0

    # Obtener detalle SOLO si existe
    - name: Obtener detalle del CLF
      command: oc get clusterlogforwarder {{ clf_name }} -n {{ logging_ns }} -o json
      register: clf_detail
      failed_when: false
      when: clf_exists

    # Validar configuración de AUDIT
    - name: Validar configuración de AUDIT
      set_fact:
        audit_configured: >-
          {{
            (
              (clf_detail.stdout | from_json)['spec']['inputs'] | default([])
              | selectattr('type', 'equalto', 'audit')
              | list
              | length > 0
            )
            or
            (
              (clf_detail.stdout | from_json)['spec']['pipelines'] | default([])
              | map(attribute='inputRefs')
              | flatten
              | select('equalto', 'audit')
              | list
              | length > 0
            )
          }}
      when: clf_exists

    # Obtener nodos
    - name: Obtener cantidad de nodos
      command: oc get nodes -o json
      register: nodes_result
      failed_when: false

    - name: Definir cantidad de nodos
      set_fact:
        node_count: "{{ (nodes_result.stdout | from_json)['items'] | length }}"
      when: nodes_result.rc == 0

    # DaemonSet collector (seguro)
    - name: Obtener DaemonSet collector
      command: oc get daemonset -n {{ logging_ns }} -l component=collector -o json
      register: ds_result
      failed_when: false

    - name: Obtener cantidad de pods collector
      set_fact:
        clf_pod_count: >-
          {{
            (ds_result.stdout | from_json)['items'][0]['status']['numberReady']
            if ((ds_result.stdout | from_json)['items'] | length > 0)
            else 0
          }}

    - name: Validar pods vs nodos
      set_fact:
        pods_ok: "{{ clf_pod_count | int == node_count | int }}"

    # ÚNICA SALIDA FINAL
    - name: Definir resultado final
      set_fact:
        resultado_final: >-
          {% if not clf_exists %}
          CLF NO EXISTE
          {% elif clf_exists and not audit_configured %}
          CLF {{ clf_name }} EXISTE - AUDIT NO CONFIGURADO
          {% elif clf_exists and audit_configured and not pods_ok %}
          CLF {{ clf_name }} EXISTE - AUDIT CONFIGURADO - PODS {{ clf_pod_count }}/{{ node_count }} (INCORRECTO)
          {% else %}
          CLF {{ clf_name }} EXISTE - AUDIT CONFIGURADO - PODS {{ clf_pod_count }}/{{ node_count }} (CORRECTO)
          {% endif %}

    - name: Mostrar resultado final
      debug:
        msg: "{{ resultado_final }}"
