---
- name: Revisión informativa de controles de seguridad OpenShift y generación de reporte
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    # =========================================================
    # INICIALIZACIÓN
    # =========================================================

    - name: Inicializar variables
      set_fact:
        cluster_name: DESCONOCIDO

    # =========================================================
    # NOMBRE DEL CLUSTER
    # =========================================================

    - name: Obtener infraestructura del cluster (API OpenShift)
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info
    
    - name: Definir nombre del cluster
      set_fact:
        cluster_name: >-
          {{
            infra_info.resources[0].status.infrastructureName
            | default('DESCONOCIDO')
          }}

    - debug:
        msg: "{{ cluster_name }}"
