---
- name: Validar si kubeadmin puede ser eliminado
  hosts: localhost
  gather_facts: no
  vars:
    kubeadmin_secret: "kubeadmin"
    kube_system_ns: "kube-system"

  tasks:

    - command: oc login --token=sha256~Vzx-JOKYuhDm47zE8bqD6gG4LZy0F_TS5EUgpXuAbSk --server=https://api.cluster-g9bkz.g9bkz.sandbox3232.opentlc.com:6443  --insecure-skip-tls-verify

    - name: Obtener configuración de OAuth del cluster
      command: oc get oauth cluster -o json
      register: oauth_config
      failed_when: oauth_config.rc != 0

    - name: Obtener identity providers configurados
      set_fact:
        identity_providers: "{{ (oauth_config.stdout | from_json).spec.identityProviders | default([]) }}"

    - name: Verificar si existen Identity Providers
      set_fact:
        has_identity_provider: "{{ identity_providers | length > 0 }}"

    - name: Verificar si el secreto kubeadmin existe
      command: oc get secret {{ kubeadmin_secret }} -n {{ kube_system_ns }}
      register: kubeadmin_secret_status
      failed_when: false

    - name: Definir mensaje final
      set_fact:
        resultado_final: >-
          {% if kubeadmin_secret_status.rc != 0 %}
          KUBEADMIN NO EXISTE - NO ES NECESARIO ELIMINAR
          {% elif kubeadmin_secret_status.rc == 0 and not has_identity_provider %}
          KUBEADMIN EXISTE - IDENTITY PROVIDER NO: NO SE PUEDE ELIMINAR
          {% elif kubeadmin_secret_status.rc == 0 and has_identity_provider %}
          KUBEADMIN EXISTE - IDENTITY PROVIDER SI: ES POSIBLE ELIMINAR
          {% endif %}

    - name: Mostrar resultado final
      debug:
        msg: "{{ resultado_final }}"
