# FUNCIONAL / PROBADO / INFORM-ENFORCE
---
- name: "Compliance OAuth - Inform & Enforce (Filtro por Cliente)"
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # Variables del Survey
    # compliance_mode: inform | enforce
    # oauth_client: "nombre1, nombre2" (Dejar vacío para TODOS)
    compliance_id: "ocp4-pci-dss-4-0-oauth-or-oauthclient-inactivity-timeout"
    
    # Valores de Remediación
    target_global_timeout: "10m0s"
    target_client_timeout_seconds: 600

    # Configuración de Reporte
    report_dir: /tmp/compliance-reports
    report_name: "oauth-audit-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

  tasks:
    - name: "Obtener infraestructura del cluster"
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: "Set cluster fact"
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('DESCONOCIDO') }}"

    - name: "[INFORM] Obtener configuración global de OAuth"
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: OAuth
        name: cluster
      register: oauth_global_info

    - name: "[INFORM] Obtener lista de OAuthClients"
      kubernetes.core.k8s_info:
        api_version: oauth.openshift.io/v1
        kind: OAuthClient
      register: oauth_clients_info

    # =========================================================
    # LÓGICA DE FILTRADO (Soporta múltiples formatos de entrada)
    # =========================================================
    - name: "Procesar lista de clientes (oauth_client)"
      set_fact:
        target_client_list: >-
          {{ 
            oauth_client.replace('\n', ',').split(',') 
            | map('trim') 
            | reject('equalto', '') 
            | list 
          }}
      when: oauth_client is defined and oauth_client | trim != ''

    - name: "Determinar clientes finales para la acción"
      set_fact:
        clients_to_process: >-
          {{
            oauth_clients_info.resources 
            | selectattr('metadata.name', 'in', target_client_list) 
            | list if (oauth_client is defined and oauth_client | trim != '') 
            else oauth_clients_info.resources | default([])
          }}

    # =========================================================
    # FASE 2: REMEDIACIÓN (ENFORCE)
    # =========================================================
    - name: "[ENFORCE] Parchear timeout global de OAuth"
      kubernetes.core.k8s:
        state: patched
        api_version: config.openshift.io/v1
        kind: OAuth
        name: cluster
        definition:
          spec:
            tokenConfig:
              accessTokenInactivityTimeout: "{{ target_global_timeout }}"
      when: compliance_mode == 'enforce'

    - name: "[ENFORCE] Parchear timeouts en OAuthClients seleccionados"
      kubernetes.core.k8s:
        state: patched
        api_version: oauth.openshift.io/v1
        kind: OAuthClient
        name: "{{ item.metadata.name }}"
        definition:
          accessTokenInactivityTimeoutSeconds: "{{ target_client_timeout_seconds }}"
      loop: "{{ clients_to_process }}"
      when: 
        - compliance_mode == 'enforce'
        - clients_to_process | length > 0

    # =========================================================
    # RE-VERIFICACIÓN Y REPORTE
    # =========================================================
    - name: "Obtener estado final para el reporte"
      kubernetes.core.k8s_info:
        api_version: oauth.openshift.io/v1
        kind: OAuthClient
      register: oauth_clients_final

    - name: "Construir reporte de auditoría"
      set_fact:
        report_text: |
          REPORTE DE CUMPLIMIENTO OAUTH: {{ compliance_mode | upper }}
          =============================================
          Cluster: {{ cluster_name }}
          Modo: {{ compliance_mode }}
          Filtro aplicado (oauth_client): {{ oauth_client if (oauth_client is defined and oauth_client != '') else 'TODOS' }}
          
          1. CONFIGURACIÓN GLOBAL (OAuth Server)
          ---------------------------------------------
          Timeout Actual: {{ oauth_global_info.resources[0].spec.tokenConfig.accessTokenInactivityTimeout | default('NO CONFIGURADO') }}
          
          2. DETALLE DE CLIENTES (OAuthClients)
          ---------------------------------------------
          {% for client in oauth_clients_final.resources | sort(attribute='metadata.name') %}
          {% set is_selected = (target_client_list is defined and client.metadata.name in target_client_list) or (oauth_client is not defined or oauth_client | trim == '') %}
          Cliente: {{ client.metadata.name }}
          Timeout: {{ client.accessTokenInactivityTimeoutSeconds | default('N/A') }} s
          ¿Fue modificado?: {{ 'SI' if is_selected and compliance_mode == 'enforce' else 'NO' }}
          ---------------------------------------------
          {% endfor %}
          =============================================

    - name: "Generar y enviar archivos de reporte"
      block:
        - name: "Crear directorio"
          file: { path: "{{ report_dir }}", state: directory, mode: '0755' }
        - name: "Guardar TXT"
          copy:
            dest: "{{ report_dir }}/{{ report_name }}.txt"
            content: "{{ report_text }}"
            mode: '0644'
        - name: "Enviar correo"
          community.general.mail:
            host: "{{ smtp_host }}"
            port: 587
            username: "{{ mail_from }}"
            password: "{{ mail_password }}"
            to: "{{ mail_to }}"
            from: "{{ mail_from }}"
            subject: "Cumplimiento OAuth: {{ cluster_name }}"
            body: "{{ report_text }}"
            secure: starttls
          when: send_mail | bool
