---
- name: ComplianceRemediations - Remote Cluster via API
  hosts: localhost
  gather_facts: no
  connection: local  # Volvemos a local para evitar el error de SSH

  vars:
    compliance_mode: inform
    remediation_name: ""
    
    # --- CONFIGURACIÓN DE CORREO ---
    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

    # --- REPORTE ---
    report_dir: /tmp/ocp-reports
    report_name: "reporte-compliance-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    # --- AUTENTICACIÓN REMOTA ---
    # Estas variables capturan el Token y la URL de la credencial de OpenShift 
    # que seleccionaste en el Job Template del Controller (AAP/AWX).
    k8s_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
    k8s_token: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"

  tasks:
    - name: Validar si la credencial fue inyectada
      fail:
        msg: "No se detectó la credencial de OpenShift. Asegúrate de asociarla al Job Template."
      when: k8s_host == "" or k8s_token == ""

    - name: Obtener infraestructura del cluster destino
      kubernetes.core.k8s_info:
        host: "{{ k8s_host }}"
        api_key: "{{ k8s_token }}"
        validate_certs: no
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('REMOTO-DESCONOCIDO') }}"

    - name: Obtener ComplianceRemediations del cluster destino
      kubernetes.core.k8s_info:
        host: "{{ k8s_host }}"
        api_key: "{{ k8s_token }}"
        validate_certs: no
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info

    - name: Definir lista de remediaciones
      set_fact:
        complianceremediations: "{{ remediation_info.resources | default([]) }}"

    - name: Filtrar remediaciones
      set_fact:
        remediations_to_apply: "{{ complianceremediations | selectattr('metadata.name', 'equalto', remediation_name) | list if remediation_name != '' else complianceremediations }}"

    - name: Aplicar ComplianceRemediations (Enforce) en cluster remoto
      kubernetes.core.k8s:
        host: "{{ k8s_host }}"
        api_key: "{{ k8s_token }}"
        validate_certs: no
        state: present
        definition:
          apiVersion: compliance.openshift.io/v1alpha1
          kind: ComplianceRemediation
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ item.metadata.namespace }}"
          spec:
            apply: true
      loop: "{{ remediations_to_apply }}"
      when: 
        - compliance_mode == 'enforce'
        - remediations_to_apply | length > 0

    - name: Construir reporte detallado
      set_fact:
        report_text: |
          REPORTE DE COMPLIANCE REMEDIATIONS
          =============================================
          Cluster Destino: {{ cluster_name }}
          API Host: {{ k8s_host }}
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Modo: {{ compliance_mode }}
          Total detectadas: {{ complianceremediations | length }}

          LISTADO DE REMEDIACIONES ENCONTRADAS:
          ---------------------------------------------
          {% if complianceremediations | length > 0 %}
          {% for r in complianceremediations %}
          - {{ r.metadata.name }} [{{ r.status.applicationState | default('N/A') }}] en namespace {{ r.metadata.namespace }}
          {% endfor %}
          {% else %}
          No se encontraron remediaciones en el cluster remoto.
          {% endif %}
          =============================================

    - name: Crear directorio y guardar archivo en el runner
      block:
        - file:
            path: "{{ report_dir }}"
            state: directory
            mode: '0755'
        - copy:
            dest: "{{ report_dir }}/{{ report_name }}.txt"
            content: "{{ report_text }}"
            mode: '0644'

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        port: 587
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "Reporte Compliance: {{ cluster_name }}"
        body: "{{ report_text }}"
        secure: starttls
      when: send_mail | bool
