---
- name: ComplianceRemediations - Survey Ready Version
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # Estas variables vendrán del Survey del AAP
    # compliance_mode: "inform" o "enforce"
    # remediation_name: "nombre1, nombre2, nombre3" (TextArea)
    
    report_dir: /tmp/ocp-reports
    report_name: "reporte-compliance-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
    
    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

  tasks:
    - name: Validar modo de ejecución
      assert:
        that:
          - compliance_mode in ['inform', 'enforce']
        fail_msg: "El modo debe ser 'inform' o 'enforce'"

    - name: Obtener infraestructura del cluster
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('DESCONOCIDO') }}"

    - name: Obtener ComplianceRemediations iniciales
      kubernetes.core.k8s_info:
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info_initial

    # =========================================================
    # LÓGICA DE FILTRADO PARA SURVEY (Soporta comas y saltos de línea)
    # =========================================================
    - name: Procesar y filtrar remediaciones seleccionadas
      set_fact:
        target_list: >-
          {{ 
            remediation_name.replace('\n', ',').split(',') 
            | map('trim') 
            | reject('equalto', '') 
            | list 
          }}
      when: remediation_name | trim != ''

    - name: Definir remediaciones a aplicar
      set_fact:
        remediations_to_apply: >-
          {{
            remediation_info_initial.resources 
            | selectattr('metadata.name', 'in', target_list) 
            | list if remediation_name | trim != '' 
            else remediation_info_initial.resources | default([])
          }}

    # =========================================================
    # APLICACIÓN (ENFORCE)
    # =========================================================
    - name: Aplicar ComplianceRemediations (Enforce)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: compliance.openshift.io/v1alpha1
          kind: ComplianceRemediation
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ item.metadata.namespace }}"
          spec:
            apply: true
      loop: "{{ remediations_to_apply }}"
      when:
        - compliance_mode == 'enforce'
        - remediations_to_apply | length > 0

    - name: Esperar brevemente actualización del estado
      pause:
        seconds: 8
      when: compliance_mode == 'enforce' and remediations_to_apply | length > 0

    # =========================================================
    # REPORTE FINAL ACTUALIZADO
    # =========================================================
    - name: Obtener estado final de las remediaciones
      kubernetes.core.k8s_info:
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info_final

    - name: Construir texto del reporte
      set_fact:
        report_text: |
          REPORTE DE COMPLIANCE REMEDIATIONS - OPENSHIFT
          =============================================
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}
          Modo: {{ compliance_mode }}
          Total detectadas: {{ remediation_info_final.resources | length }}

          DETALLE DE POLÍTICAS EN EL CLUSTER:
          ---------------------------------------------
          {% if remediation_info_final.resources | length == 0 %}
          No se encontraron remediaciones.
          {% else %}
          {% for r in remediation_info_final.resources %}
          - Nombre: {{ r.metadata.name }}
            Estado: {{ r.status.applicationState | default('PROCESANDO/PENDIENTE') }}
            Namespace: {{ r.metadata.namespace }}
            {% if target_list is defined and r.metadata.name in target_list %}
            ACCIONADA: SI (Solicitada por Survey)
            {% elif remediation_name | trim == '' %}
            ACCIONADA: SI (Procesando todas)
            {% else %}
            ACCIONADA: NO (Omitida)
            {% endif %}
          ---------------------------------------------
          {% endfor %}
          {% endif %}

          RESUMEN DE EJECUCIÓN:
          {% if compliance_mode == 'enforce' %}
          Se proceso la aplicacion de {{ remediations_to_apply | length }} remediacion(es).
          {% else %}
          Modo informativo. No se realizaron cambios.
          {% endif %}
          =============================================

    - name: Crear directorio y guardar TXT local
      block:
        - name: Directorio
          file: { path: "{{ report_dir }}", state: directory, mode: '0755' }
        - name: Guardar archivo
          copy:
            dest: "{{ report_dir }}/{{ report_name }}.txt"
            content: "{{ report_text }}"
            mode: '0644'

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        port: 587
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "Reporte Compliance: {{ cluster_name }} ({{ compliance_mode }})"
        body: "{{ report_text }}"
        secure: starttls
      when: send_mail | bool
