---
- name: ComplianceRemediations - Forced Manual Connection
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # Estas variables las definiremos manualmente en el AAP (Extra Vars)
    # o las tomaremos de las variables de entorno limpias
    compliance_mode: inform
    remediation_name: ""
    
    # --- DATOS DE NOTIFICACIÓN ---
    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

    # --- REPORTE ---
    report_dir: /tmp/ocp-reports
    report_name: "reporte-compliance-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

  tasks:
    - name: "DEBUG - Verificar qué está inyectando el AAP realmente"
      debug:
        msg: 
          - "K8S_AUTH_HOST: {{ lookup('env', 'K8S_AUTH_HOST') }}"
          - "K8S_AUTH_API_KEY (primeros 10 caracteres): {{ lookup('env', 'K8S_AUTH_API_KEY') | truncate(10) }}"

    - name: "Configurar conexión al cluster destino"
      set_fact:
        # Priorizamos variables manuales si existen, sino usamos las del entorno
        target_host: "{{ manual_k8s_host | default(lookup('env', 'K8S_AUTH_HOST')) }}"
        target_token: "{{ manual_k8s_token | default(lookup('env', 'K8S_AUTH_API_KEY')) }}"

    - name: Obtener infraestructura del cluster DESTINO
      kubernetes.core.k8s_info:
        kubeconfig: /dev/null
        host: "{{ target_host }}"
        api_key: "{{ target_token }}"
        validate_certs: no
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('ERROR') }}"

    - name: Obtener ComplianceRemediations
      kubernetes.core.k8s_info:
        kubeconfig: /dev/null
        host: "{{ target_host }}"
        api_key: "{{ target_token }}"
        validate_certs: no
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info

    # ... (Resto de las tareas de filtrado, reporte y correo igual que antes) ...

    - name: Construir reporte final
      set_fact:
        report_text: |
          REPORTE DE COMPLIANCE - DIAGNÓSTICO
          =============================================
          Cluster Detectado: {{ cluster_name }}
          URL de API usada: {{ target_host }}
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Total Remediaciones: {{ remediation_info.resources | length | default(0) }}
          =============================================

    - name: Enviar Correo
      community.general.mail:
        host: "{{ smtp_host }}"
        port: 587
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "DIAGNÓSTICO Compliance: {{ cluster_name }}"
        body: "{{ report_text }}"
        secure: starttls
      when: send_mail | bool
