---
- name: Reporte de ComplianceRemediations OpenShift
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # =========================
    # REPORTE
    # =========================
    report_dir: /tmp/ocp-reports
    report_name: "reporte-compliance-remediations-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    # =========================
    # ENVÍO DE CORREO
    # =========================

    send_mail: true
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

  tasks:

    # =========================================================
    # OBTENER NOMBRE DEL CLUSTER
    # =========================================================

    - name: Obtener infraestructura del cluster
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: >-
          {{
            infra_info.resources[0].status.infrastructureName
            | default('DESCONOCIDO')
          }}

    # =========================================================
    # OBTENER COMPLIANCE REMEDIATIONS
    # =========================================================

    - name: Obtener ComplianceRemediations del cluster
      kubernetes.core.k8s_info:
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info

    - name: Definir lista de remediaciones
      set_fact:
        complianceremediations: "{{ remediation_info.resources | default([]) }}"

    # =========================================================
    # CONSTRUIR REPORTE
    # =========================================================

    - name: Construir reporte de ComplianceRemediations
      set_fact:
        report_text: |
          REPORTE DE COMPLIANCE REMEDIATIONS - OPENSHIFT
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}

          Total de remediaciones encontradas: {{ complianceremediations | length }}

          ---------------------------------
          LISTADO DE REMEDIACIONES
          ---------------------------------
          {% if complianceremediations | length == 0 %}
          No se encontraron ComplianceRemediations en el cluster.
          {% else %}
          {% for r in complianceremediations %}
          Nombre: {{ r.metadata.name }}
          Namespace: {{ r.metadata.namespace }}
          Estado aplicación: {{ r.status.applicationState | default('DESCONOCIDO') }}
          Tipo: {{ r.spec.type | default('N/A') }}
          ---------------------------------
          {% endfor %}
          {% endif %}

    # =========================================================
    # GUARDAR REPORTE
    # =========================================================

    - name: Crear directorio de reportes
      file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'

    - name: Guardar reporte en archivo
      copy:
        dest: "{{ report_dir }}/{{ report_name }}.txt"
        content: "{{ report_text }}"
        mode: '0644'

    # =========================================================
    # ENVÍO POR CORREO
    # =========================================================

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "Reporte ComplianceRemediations OpenShift - {{ cluster_name }}"
        body: "{{ report_text }}"
      when: send_mail
