---
- name: ComplianceRemediations - Full Lifecycle
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    # --- MODO DE EJECUCIÓN ---
    compliance_mode: inform  # inform | enforce
    remediation_name: ""      # Opcional: nombre de una remediación específica

    # --- CONFIGURACIÓN DE ENVÍO ---
    send_mail: true
    send_webhook: false
    
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com
    
    webhook_url: "https://tu-url-de-webhook.com"

  tasks:
    - name: Validar modo de ejecución
      assert:
        that:
          - compliance_mode in ['inform', 'enforce']
        fail_msg: "compliance_mode debe ser 'inform' o 'enforce'"

    - name: Obtener infraestructura del cluster
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('DESCONOCIDO') }}"

    - name: Obtener ComplianceRemediations
      kubernetes.core.k8s_info:
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info

    - name: Definir lista de remediaciones
      set_fact:
        complianceremediations: "{{ remediation_info.resources | default([]) }}"

    # --- LÓGICA DE FILTRADO Y APLICACIÓN (ENFORCE) ---
    - name: Filtrar remediaciones a aplicar
      set_fact:
        remediations_to_apply: >-
          {{
            complianceremediations 
            | selectattr('metadata.name', 'equalto', remediation_name) 
            | list if remediation_name | length > 0 
            else complianceremediations
          }}
      when: compliance_mode == 'enforce'

    - name: Aplicar ComplianceRemediations (Enforce)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: compliance.openshift.io/v1alpha1
          kind: ComplianceRemediation
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ item.metadata.namespace }}"
          spec:
            apply: true
      loop: "{{ remediations_to_apply | default([]) }}"
      when: 
        - compliance_mode == 'enforce'
        - remediations_to_apply | length > 0

    # --- CONSTRUCCIÓN DEL REPORTE ---
    - name: Construir reporte en texto plano
      set_fact:
        report_text: |
          REPORTE DE COMPLIANCE REMEDIATIONS - OPENSHIFT
          =============================================
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}
          Modo de ejecución: {{ compliance_mode }}
          Total detectadas: {{ complianceremediations | length }}

          DETALLE DE REMEDIACIONES:
          {% if complianceremediations | length == 0 %}
          No se encontraron remediaciones.
          {% else %}
          {% for r in complianceremediations %}
          - Nombre: {{ r.metadata.name }}
            Estado: {{ r.status.applicationState | default('N/A') }}
            Namespace: {{ r.metadata.namespace }}
          {% endfor %}
          {% endif %}

          RESULTADO DE LA ACCIÓN:
          {% if compliance_mode == 'inform' %}
          Modo informativo: No se realizaron cambios.
          {% elif remediations_to_apply | default([]) | length > 0 %}
          Se intentó aplicar {{ remediations_to_apply | length }} remediación(es).
          {% else %}
          No había remediaciones para aplicar.
          {% endif %}
          =============================================

    # --- ENVÍOS ---
    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        port: 587
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "Reporte Compliance ({{ compliance_mode }}): {{ cluster_name }}"
        body: "{{ report_text }}"
        secure: starttls
      when: send_mail | bool

    - name: Enviar reporte por Webhook
      ansible.builtin.uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        body:
          text: "{{ report_text }}"
        status_code: [200, 201, 204]
      when: send_webhook | bool
