---
- name: ComplianceRemediations - Full Lifecycle
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    compliance_mode: inform
    remediation_name: ""
    report_dir: /tmp/ocp-reports
    report_name: "reporte-compliance-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
    send_mail: true
    
    mail_to: jmunozag@redhat.com
    mail_from: botkev838@gmail.com
    mail_password: "qfni wfkv uxsw dyjf"
    smtp_host: smtp.gmail.com

  tasks:
    - name: Obtener infraestructura del cluster
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: infra_info

    - name: Definir nombre del cluster
      set_fact:
        cluster_name: "{{ infra_info.resources[0].status.infrastructureName | default('DESCONOCIDO') }}"

    - name: Obtener ComplianceRemediations
      kubernetes.core.k8s_info:
        api_version: compliance.openshift.io/v1alpha1
        kind: ComplianceRemediation
      register: remediation_info

    - name: Definir lista base de remediaciones
      set_fact:
        complianceremediations: "{{ remediation_info.resources | default([]) }}"

    - name: Filtrar remediaciones (Lista específica o todas)
      set_fact:
        remediations_to_apply: "{{ complianceremediations | selectattr('metadata.name', 'equalto', remediation_name) | list if remediation_name != '' else complianceremediations }}"

    - name: Aplicar ComplianceRemediations (Enforce)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: compliance.openshift.io/v1alpha1
          kind: ComplianceRemediation
          metadata:
            name: "{{ item.metadata.name }}"
            namespace: "{{ item.metadata.namespace }}"
          spec:
            apply: true
      loop: "{{ remediations_to_apply }}"
      when: 
        - compliance_mode == 'enforce'
        - remediations_to_apply | length > 0

    - name: Construir reporte en texto plano
      set_fact:
        report_text: |
          REPORTE DE COMPLIANCE REMEDIATIONS - OPENSHIFT
          =============================================
          Fecha: {{ lookup('pipe', 'date --iso-8601=seconds') }}
          Cluster: {{ cluster_name }}
          Modo de ejecución: {{ compliance_mode }}
          Total detectadas: {{ complianceremediations | length }}

          DETALLE DE REMEDIACIONES ENCONTRADAS:
          -------------------------
          {% if complianceremediations | length > 0 %}
          {% for r in complianceremediations %}
          - Nombre: {{ r.metadata.name }}
            Estado: {{ r.status.applicationState | default('N/A') }}
            Namespace: {{ r.metadata.namespace }}
          {% endfor %}
          {% else %}
          No se encontraron objetos ComplianceRemediation en el cluster.
          {% endif %}

          RESULTADO DE LA ACCIÓN:
          -------------------------
          {% if compliance_mode == 'inform' %}
          Modo informativo: No se realizaron cambios.
          {% elif remediations_to_apply | length > 0 %}
          Se proceso la aplicacion de {{ remediations_to_apply | length }} remediacion(es).
          {% else %}
          No habia remediaciones para aplicar.
          {% endif %}
          =============================================

    - name: Crear directorio y guardar archivo
      block:
        - name: Crear directorio
          file:
            path: "{{ report_dir }}"
            state: directory
            mode: '0755'
        - name: Guardar reporte
          copy:
            dest: "{{ report_dir }}/{{ report_name }}.txt"
            content: "{{ report_text }}"
            mode: '0644'

    - name: Enviar reporte por correo
      community.general.mail:
        host: "{{ smtp_host }}"
        port: 587
        username: "{{ mail_from }}"
        password: "{{ mail_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "Reporte Compliance ({{ compliance_mode }}): {{ cluster_name }}"
        body: "{{ report_text }}"
        secure: starttls
      when: send_mail | bool
