---
- name: Revisión LDAP Identity Providers (TLS)
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - command: oc login --token=sha256~a7NNKc8Nu_eEFexkQ0TMZRsg2k7wCgs8f6LRbS4l4s0 --server=https://api.cluster-g9bkz.g9bkz.sandbox3232.opentlc.com:6443 --insecure-skip-tls-verify

    - name: Obtener configuración OAuth del cluster
      command: oc get oauth cluster -o json
      register: oauth_result
      failed_when: false

    - name: Extraer Identity Providers
      set_fact:
        identity_providers: "{{ (oauth_result.stdout | from_json)['spec']['identityProviders'] | default([]) }}"

    - name: Filtrar Identity Providers de tipo LDAP
      set_fact:
        ldap_idps: "{{ identity_providers | selectattr('type', 'equalto', 'LDAP') | list }}"

    - name: Definir resultado final
      set_fact:
        resultado_final: >-
          {% if ldap_idps | length == 0 %}
          NO EXISTEN IDENTITY PROVIDERS LDAP CONFIGURADOS
          {% else %}
          {% for idp in ldap_idps %}
          IDP LDAP: {{ idp.name }} - INSECURE: {{ idp.ldap.insecure | default(false) }}
          {% endfor %}
          {% endif %}

    - name: Mostrar resultado final
      debug:
        msg: "{{ resultado_final }}"
